### PR TITLE
新增高雄的診所資料

### PR DESCRIPTION
**Pull request by Li-Pro**
用 https://github.com/CMUH-CMAX/Crawler 取得高雄的診所資料，並新增在 `data/clinics.jsonl` 裡了。

### CODE REVIEW

**Comment by ZoneTwelve** [comment]
Could you please help me confirm whether any information is missing?
Because I don't think there are only 159 clinics.

**Comment by Li-Pro** [comment]
I saw there were ~419~ clinics according to http://www.tcm.tw/city.php?areaid=018&type=CM.  
Strange. Seems that I shouldn't assume the crawler would always success.

EDIT: [there are 441 clinics](http://www.tcm.tw/city2.php?areaid=018)

**Comment by Li-Pro** [comment]
BTW, though I were able to read from the repository https://github.com/CMUH-CMAX/Crawler, I could not write (push) to it.  
Do I need to join a related team? I can work on to improve the crawler.

**Comment by Li-Pro** [comment]
Hi @ZoneTwelve，我把高雄市的資料補上去了，總共有 441 個診所。  
另外台中有 734 筆，我把缺少的也補上去了 (原本有 717 筆)。  

在這些資料裡面我找到一個特別的診所：高雄的[福山雲玖中醫診所](http://www.tcm.tw/city2.php?areaid=018&page=6)，他沒有提供電話。也許我們的 database schema 可能要改一下...?

**Comment by ZoneTwelve** [comment]
> Hi @ZoneTwelve，我把高雄市的資料補上去了，總共有 441 個診所。 另外台中有 734 筆，我把缺少的也補上去了 (原本有 717 筆)。
> 
> 在這些資料裡面我找到一個特別的診所：高雄的[福山雲玖中醫診所](http://www.tcm.tw/city2.php?areaid=018&page=6)，他沒有提供電話。也許我們的 database schema 可能要改一下...?

Thank you for all of that work, but I think we can leave it blank and keep it as is.

**Pull request merged**
